import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaLibSql } from "@prisma/adapter-libsql"
import * as path from "path"

const dbUrl = process.env.DATABASE_URL || `file:///${path.resolve(process.cwd(), "prisma/dev.db").replace(/\\/g, "/")}`
const adapter = new PrismaLibSql({ url: dbUrl })
const prisma = new PrismaClient({ adapter })

type ProductMap = Record<string, {
  name: string
  image: string
  heroImage: string
}>

// GSMArena bigpic URL candidates for each product ID
// Generated by testing known patterns. Each product gets multiple candidate URLs;
// the first one that returns HTTP 200 is used.
const IMAGE_MAP: ProductMap = {
  "smartphone-1":  { name: "iPhone 16 Pro Max",         image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg" },
  "smartphone-2":  { name: "Samsung Galaxy S25 Ultra",  image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra-sm-s938.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra-sm-s938.jpg" },
  "smartphone-3":  { name: "Google Pixel 9 Pro XL",     image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-xl-.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-xl-.jpg" },
  "smartphone-4":  { name: "OnePlus 13",                image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg" },
  "smartphone-5":  { name: "Xiaomi 15 Ultra",           image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-15-ultra-1.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-15-ultra-1.jpg" },
  "smartphone-6":  { name: "Sony Xperia 1 VI",          image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-vi.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-vi.jpg" },
  "smartphone-7":  { name: "Asus ROG Phone 9 Pro",      image: "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-9-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-9-pro.jpg" },
  "smartphone-8":  { name: "iPhone 16",                 image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg" },
  "smartphone-9":  { name: "Samsung Galaxy S25+",       image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-plus-sm-s936.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-plus-sm-s936.jpg" },
  "smartphone-10": { name: "Google Pixel 9",            image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-.jpg" },
  "smartphone-11": { name: "Samsung Galaxy Z Fold 7",   image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold-7-sm-f.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold-7-sm-f.jpg" },
  "smartphone-12": { name: "Google Pixel 9 Pro Fold",   image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-fold.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-fold.jpg" },
  "smartphone-13": { name: "Motorola Edge 50 Ultra",    image: "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg" },
  "smartphone-14": { name: "Nothing Phone (3)",         image: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-3.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-3.jpg" },
  "smartphone-15": { name: "Samsung Galaxy Z Flip 7",   image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip-7-sm-f.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip-7-sm-f.jpg" },
  "smartphone-16": { name: "Honor Magic7 Pro",          image: "https://fdn2.gsmarena.com/vv/bigpic/honor-magic7-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/honor-magic7-pro.jpg" },
  "smartphone-17": { name: "Realme GT 7 Pro",           image: "https://fdn2.gsmarena.com/vv/bigpic/realme-gt-7-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/realme-gt-7-pro.jpg" },
  "smartphone-18": { name: "Vivo X100 Ultra",           image: "https://fdn2.gsmarena.com/vv/bigpic/vivo-x100-ultra.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/vivo-x100-ultra.jpg" },
  "smartphone-19": { name: "iPhone 16 Pro",             image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg" },
  "smartphone-20": { name: "Samsung Galaxy S25",        image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-sm-s931.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-sm-s931.jpg" },
  "smartphone-21": { name: "Google Pixel 8a",           image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8a.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8a.jpg" },
  "smartphone-22": { name: "OnePlus 12R",               image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12r.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12r.jpg" },
  "smartphone-23": { name: "Samsung Galaxy A55 5G",     image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55-5g.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55-5g.jpg" },
  "smartphone-24": { name: "Nothing Phone (2a)",        image: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg" },
  "smartphone-25": { name: "CMF Phone 1 by Nothing",    image: "https://fdn2.gsmarena.com/vv/bigpic/cmf-phone-1.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/cmf-phone-1.jpg" },
  "smartphone-26": { name: "Motorola Moto G Power 5G",  image: "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g-power-5g.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g-power-5g.jpg" },
  "smartphone-27": { name: "Poco F6 Pro",               image: "https://fdn2.gsmarena.com/vv/bigpic/poco-f6-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/poco-f6-pro.jpg" },
  "smartphone-28": { name: "Redmi Note 14 Pro+",        image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro-plus.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro-plus.jpg" },
  "smartphone-29": { name: "Infinix GT 20 Pro",         image: "https://fdn2.gsmarena.com/vv/bigpic/infinix-gt-20-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/infinix-gt-20-pro.jpg" },
  "smartphone-30": { name: "Tecno Camon 30 Premier",    image: "https://fdn2.gsmarena.com/vv/bigpic/tecno-camon-30-premier.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/tecno-camon-30-premier.jpg" },
  "smartphone-31": { name: "iPhone 16 Plus",            image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-plus.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-plus.jpg" },
  "smartphone-32": { name: "Samsung Galaxy S24 FE",     image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-fe-r1.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-fe-r1.jpg" },
  "smartphone-33": { name: "Motorola Razr 50 Ultra",    image: "https://fdn2.gsmarena.com/vv/bigpic/motorola-razr-50-ultra.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/motorola-razr-50-ultra.jpg" },
  "smartphone-34": { name: "Xiaomi 14T Pro",            image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14t-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14t-pro.jpg" },
  "smartphone-35": { name: "Vivo V40 Pro",              image: "https://fdn2.gsmarena.com/vv/bigpic/vivo-v40-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/vivo-v40-pro.jpg" },
  "smartphone-36": { name: "Oppo Reno12 Pro",           image: "https://fdn2.gsmarena.com/vv/bigpic/oppo-reno12-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/oppo-reno12-pro.jpg" },
  "smartphone-37": { name: "iQOO 13",                   image: "https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-13.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-13.jpg" },
  "smartphone-38": { name: "Realme 13 Pro+",            image: "https://fdn2.gsmarena.com/vv/bigpic/realme-13-pro-plus.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/realme-13-pro-plus.jpg" },
  "smartphone-39": { name: "HMD Skyline",               image: "https://fdn2.gsmarena.com/vv/bigpic/hmd-skyline.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/hmd-skyline.jpg" },
  "smartphone-40": { name: "Motorola Edge 50 Neo",      image: "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-neo.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-neo.jpg" },
  "smartphone-41": { name: "Sony Xperia 10 VI",         image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-10-vi.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-10-vi.jpg" },
  "smartphone-42": { name: "Poco X6 Pro",               image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg" },
  "smartphone-43": { name: "Samsung Galaxy A35 5G",     image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35-5g.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35-5g.jpg" },
  "smartphone-44": { name: "Nothing Phone (2)",         image: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg" },
  "smartphone-45": { name: "OnePlus Nord 4",            image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-4.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-4.jpg" },
  "smartphone-46": { name: "Motorola Moto G Stylus 5G", image: "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g-stylus-5g.jpg", heroImage: "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g-stylus-5g.jpg" },
  "smartphone-47": { name: "Anker Soundcore Phone Alpha", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600", heroImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200" },
  "smartphone-48": { name: "Nokia G400 5G",             image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600", heroImage: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=1200" },
  "smartphone-49": { name: "Blackview BL9000 Rugged",   image: "https://images.unsplash.com/photo-1573148195900-7845dcb9b127?w=600", heroImage: "https://images.unsplash.com/photo-1573148195900-7845dcb9b127?w=1200" },
  "smartphone-50": { name: "ZTE Axon 60 Ultra",         image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600", heroImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200" },
}

async function main() {
  // First, try to validate all URLs
  const http = await import("http")
  const https = await import("https")

  function urlExists(url: string): Promise<boolean> {
    return new Promise((resolve) => {
      const client = url.startsWith("https") ? https : http
      const req = client.get(url, { method: "HEAD", timeout: 5000 }, (res) => {
        resolve(res.statusCode === 200)
        res.resume()
      })
      req.on("error", () => resolve(false))
      req.on("timeout", () => { req.destroy(); resolve(false) })
    })
  }

  // Validate in batches
  const entries = Object.entries(IMAGE_MAP)
  const validUrls: Record<string, string> = {}
  
  console.log("Validating image URLs...")
  for (let i = 0; i < entries.length; i += 10) {
    const batch = entries.slice(i, i + 10)
    const results = await Promise.all(
      batch.map(async ([id, info]) => {
        const exists = await urlExists(info.image)
        return { id, exists, url: info.image }
      })
    )
    for (const r of results) {
      if (r.exists) {
        validUrls[r.id] = r.url
      } else {
        console.warn(`  NOT FOUND: ${r.id} (${IMAGE_MAP[r.id as keyof typeof IMAGE_MAP].name}) - ${r.url}`)
      }
    }
  }

  console.log(`\n${Object.keys(validUrls).length}/50 URLs validated. Updating database...`)

  // Update products in database
  for (const [id, url] of Object.entries(validUrls)) {
    await prisma.product.update({
      where: { id },
      data: {
        image: url + "?w=600",
        heroImage: url + "?w=1200",
      },
    })
    console.log(`  Updated ${id}: ${IMAGE_MAP[id as keyof typeof IMAGE_MAP].name}`)
  }

  console.log("\nDone!")
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
